"use strict";
module.exports = {
  allowedOrigins: [
    "http://localhost",
    "https://totalcollectr.dev",
    "https://totalcollectr.codes",
    "https://mygbcollects.com",
    "https://latest.mysageaccount.com",
    "https://creditninjacollects.com",
    "https://demo.totalcollectr.dev",
    "https://bluefrog.totalcollectr.io",
    "https://mysageaccount.com",
    "https://payprimeaccount.com",
    "https://alliant.beamcollects.com",
    "https://cbc.totalcollectr.io",
    "https://financesystems.totalcollectr.io",
    "https://fundo.totalcollectr.io",
    "https://beamcollects.com",
    "https://lshholdings.totalcollectr.io",
    "https://mfs.totalcollectr.io",
    " https://ncs.totalcollectr.io",
    "https://www.norman.totalcollectr.io",
    "https://radbills.totalcollectr.io",
    "https://westlake.totalcollectr.io",
    "https://wise.totalcollectr.io",
    "https://mycreditfreshaccount.com",
    "https://mymoneykey.com",
    "https://arsclicktopay.com",
    "https://hrs-resolve.com",
    "https://empereon.totalcollectr.io",
    "https://set.totalcollectr.io",
    "https://lippman.totalcollectr.io",
    " https://myasapaccount.com",
    "https://scottandassociates-pc.com",
    "https://tbc.totalcollectr.io",
    "https://lendbearpay.com",
    "https://pacific.totalcollectr.io",
    "https://oliphant.totalcollectr.io",
    "https://rivervalley.totalcollectr.io",
    "https://nca.totalcollectr.io",
    "https://simm.totalcollectr.io",
    "https://wrightlaw.totalcollectr.io",
    "https://dca.totalcollectr.io",
    "https://dca.totalcollectr.io",
    "https://dca.totalcollectr.io",
    "https://pyxiscollects.com",
  ],
};
