"use strict";
module.exports = {
  allowedOrigins: [
    "http://localhost",
    "https://totalcollectr.dev",
    "https://totalcollectr.codes",
    "https://mygbcollects.com",
    "https://latest.mysageaccount.com",
    "https://creditninjacollects.com",
    "https://mysageaccount.com",
    "https://payprimeaccount.com",
    "https://financesystems.totalcollectr.io",
    "https://mfs.totalcollectr.io",
    "https://ncs.totalcollectr.io",
    "https://radbills.totalcollectr.io",
    "https://wise.totalcollectr.io",
    "https://mycreditfreshaccount.com",
    "https://arsclicktopay.com",
    "https://empereon.totalcollectr.io",
    "https://myasapaccount.com",
    "https://scottandassociates-pc.com",
    "https://lendbearpay.com",
    "https://nca.totalcollectr.io",
    "https://simm.totalcollectr.io",
    "https://pyxiscollects.com",
    "https://natcredsys.com",
    "https://dma.totalcollectr.io",
    "https://managemyloan.dashofcash.com",
    "https://demo.totalcollectr.io",
  ],
};
